export type RiskLevel = 'critical' | 'high' | 'medium' | 'low';

export interface DangerRule {
  id: string;
  name: string;
  description: string;
  level: RiskLevel;
  patterns: RegExp[];
  categories: string[];
  action?: 'block' | 'warn' | 'log';
}

export const DANGER_RULES: DangerRule[] = [
  // ==================== Gateway 连接 ====================
  {
    id: 'gateway-unauthorized-access',
    name: '未授权的Gateway访问',
    description: '检测未配对设备的连接尝试',
    level: 'high',
    patterns: [
      /unauthorized.*access/i,
      /authentication failed/i,
      /invalid token/i,
      /device not paired/i,
      /permission denied/i,
      /AUTH_TOKEN_MISMATCH/i,
    ],
    categories: ['gateway', 'access'],
    action: 'warn',
  },
  {
    id: 'gateway-new-device-pairing',
    name: '新设备配对请求',
    description: '检测新的设备配对请求',
    level: 'medium',
    patterns: [
      /pairing request/i,
      /device pairing/i,
      /new device.*connecting/i,
      /pending.*pairing/i,
    ],
    categories: ['gateway', 'device'],
    action: 'log',
  },
  {
    id: 'gateway-remote-connection',
    name: '远程连接Gateway',
    description: '检测来自非本地的Gateway连接',
    level: 'medium',
    patterns: [
      /connection from.*\d+\.\d+\.\d+\.\d+/i,
      /client.*\d+\.\d+\.\d+\.\d+/i,
      /remote.*connected/i,
    ],
    categories: ['gateway', 'network'],
    action: 'warn',
  },
  {
    id: 'gateway-suspicious-activity',
    name: 'Gateway可疑活动',
    description: '检测Gateway的可疑活动模式',
    level: 'high',
    patterns: [
      /brute force/i,
      /too many.*attempts/i,
      /rate limit.*exceeded/i,
      /suspicious.*request/i,
      /blocked.*ip/i,
    ],
    categories: ['gateway', 'intrusion'],
    action: 'warn',
  },

  // ==================== 文件操作 ====================
  {
    id: 'file-delete-recursive',
    name: '递归删除',
    description: '检测 rm -rf 等递归删除命令',
    level: 'critical',
    patterns: [
      /\brm\s+(-[rf]+\s+|--recursive\s+|--force\s+).*\//gi,
      /\brm\s+-rf\s+\//gi,
      /\brm\s+-rf\s+~/gi,
      /\brm\s+-rf\s+\*/gi,
    ],
    categories: ['file', 'destructive'],
    action: 'warn',
  },
  {
    id: 'file-delete-important',
    name: '删除重要文件',
    description: '检测删除重要系统文件或配置',
    level: 'critical',
    patterns: [
      /\brm\s+.*\/etc\/passwd/i,
      /\brm\s+.*\/etc\/shadow/i,
      /\brm\s+.*\.ssh\//i,
      /\brm\s+.*\.gnupg\//i,
      /\brm\s+.*\.openclaw\/openclaw\.json/i,
    ],
    categories: ['file', 'destructive', 'system'],
    action: 'block',
  },
  {
    id: 'file-access-sensitive',
    name: '访问敏感文件',
    description: '检测读取敏感文件',
    level: 'high',
    patterns: [
      /cat\s+.*\/etc\/passwd/i,
      /cat\s+.*\/etc\/shadow/i,
      /cat\s+.*\.ssh\/id_rsa/i,
      /cat\s+.*\.pem/i,
      /cat\s+.*\.key/i,
      /less\s+.*\.ssh\//i,
      /head\s+.*\.ssh\//i,
    ],
    categories: ['file', 'sensitive'],
    action: 'warn',
  },
  {
    id: 'chmod-dangerous',
    name: '危险权限修改',
    description: '检测将文件设置为全局可写或可执行',
    level: 'high',
    patterns: [
      /chmod\s+777/i,
      /chmod\s+-R\s+777/i,
      /chmod\s+\+x.*\/etc\//i,
    ],
    categories: ['file', 'permission'],
    action: 'warn',
  },

  // ==================== 网络操作 ====================
  {
    id: 'network-download-execute',
    name: '下载并执行',
    description: '检测从网络下载并直接执行的命令',
    level: 'critical',
    patterns: [
      /curl\s+.*\|\s*(bash|sh|python|node)/i,
      /wget\s+.*\|\s*(bash|sh|python|node)/i,
      /curl\s+.*>\s*.*\.sh.*&&\s*\./i,
    ],
    categories: ['network', 'destructive'],
    action: 'block',
  },
  {
    id: 'network-upload-sensitive',
    name: '上传敏感数据',
    description: '检测可能上传敏感文件的行为',
    level: 'high',
    patterns: [
      /curl\s+.*-T\s+.*\.ssh\//i,
      /curl\s+.*-T\s+.*\.pem/i,
      /curl\s+.*-T\s+.*\.key/i,
      /scp\s+.*\.ssh\//i,
      /rsync\s+.*\.ssh\//i,
    ],
    categories: ['network', 'exfiltration'],
    action: 'warn',
  },
  {
    id: 'network-reverse-shell',
    name: '反向Shell',
    description: '检测反向Shell连接',
    level: 'critical',
    patterns: [
      /bash\s+-[ci].*>.*\/dev\/tcp/i,
      /nc\s+.*-e\s+(bash|sh)/i,
      /ncat\s+.*-e\s+(bash|sh)/i,
      /python.*-c.*socket/i,
    ],
    categories: ['network', 'intrusion'],
    action: 'block',
  },

  // ==================== 系统操作 ====================
  {
    id: 'system-shutdown',
    name: '系统关机',
    description: '检测系统关机/重启命令',
    level: 'critical',
    patterns: [
      /\bshutdown\s+/i,
      /\breboot/i,
      /\binit\s+0/i,
      /\binit\s+6/i,
      /\bsystemctl\s+(reboot|poweroff)/i,
    ],
    categories: ['system', 'destructive'],
    action: 'block',
  },
  {
    id: 'system-service-modify',
    name: '修改系统服务',
    description: '检测修改系统服务的操作',
    level: 'high',
    patterns: [
      /systemctl\s+(enable|disable)\s+/i,
      /systemctl\s+mask\s+/i,
      /update-rc\.d\s+/i,
      /chkconfig\s+/i,
    ],
    categories: ['system', 'service'],
    action: 'warn',
  },
  {
    id: 'system-user-modify',
    name: '修改用户',
    description: '检测添加/修改用户操作',
    level: 'high',
    patterns: [
      /\buseradd\s+/i,
      /\busermod\s+/i,
      /\bpasswd\s+/i,
      /\badduser\s+/i,
    ],
    categories: ['system', 'user'],
    action: 'warn',
  },

  // ==================== 包管理 ====================
  {
    id: 'package-install-unknown',
    name: '安装未知包',
    description: '检测从非官方源安装软件包',
    level: 'medium',
    patterns: [
      /npm\s+install\s+.*--force/i,
      /npm\s+install\s+-g\s+[a-z]/i,
      /pip\s+install\s+.*--no-verify/i,
      /curl.*|.*sudo\s+apt/i,
    ],
    categories: ['package', 'security'],
    action: 'warn',
  },

  // ==================== OpenClaw 特定 ====================
  {
    id: 'openclaw-config-modify',
    name: '修改OpenClaw配置',
    description: '检测修改OpenClaw配置文件',
    level: 'medium',
    patterns: [
      /\.openclaw\/openclaw\.json/i,
      /openclaw\s+config\s+set/i,
    ],
    categories: ['openclaw', 'config'],
    action: 'log',
  },
  {
    id: 'openclaw-credential-expose',
    name: '凭证暴露',
    description: '检测API密钥或凭证可能被暴露',
    level: 'high',
    patterns: [
      /sk-[a-zA-Z0-9]{20,}/i,
      /[a-f0-9]{32,}/i,
      /password\s*[=:]\s*\S+/i,
      /token\s*[=:]\s*\S+/i,
      /secret\s*[=:]\s*\S+/i,
    ],
    categories: ['openclaw', 'credential'],
    action: 'warn',
  },

  // ==================== 数据操作 ====================
  {
    id: 'data-bulk-delete',
    name: '批量删除数据',
    description: '检测批量删除数据库或文件',
    level: 'critical',
    patterns: [
      /DROP\s+DATABASE/i,
      /DROP\s+TABLE/i,
      /TRUNCATE\s+TABLE/i,
      /DELETE\s+FROM\s+\w+\s*;/i,
      /mongo.*\.drop\(\)/i,
      /redis.*FLUSHALL/i,
    ],
    categories: ['data', 'destructive'],
    action: 'block',
  },
  {
    id: 'data-bulk-export',
    name: '批量导出数据',
    description: '检测可能的数据导出行为',
    level: 'medium',
    patterns: [
      /mysqldump\s+/i,
      /pg_dump\s+/i,
      /mongoexport\s+/i,
      /redis-cli.*--rdb/i,
    ],
    categories: ['data', 'exfiltration'],
    action: 'warn',
  },

  // ==================== AI Agent 特有操作 ====================
  {
    id: 'ai-auto-email',
    name: '自动发送邮件',
    description: '检测 AI 尝试自动发送邮件',
    level: 'high',
    patterns: [
      /\bsend\s+(an?\s+)?email\b/i,
      /\bsend\s+mail\b/i,
      /\bmail\s+to\b/i,
      /\bemail\s+to\b/i,
      /\bsmtp\s+send\b/i,
      /\bnodemailer\b/i,
      /\bimap\s+send\b/i,
      /\bcompose\s+email\b/i,
      /\bsendgrid\s+send\b/i,
      /\bmailgun\b/i,
    ],
    categories: ['ai-agent', 'communication', 'exfiltration'],
    action: 'warn',
  },
  {
    id: 'ai-file-upload',
    name: '文件上传到外部',
    description: '检测 AI 尝试上传文件到外部服务',
    level: 'high',
    patterns: [
      /\bupload\s+.*\bto\s+(http|ftp|s3|cloud)\b/i,
      /\bput\s+.*\bto\s+s3\b/i,
      /\bs3\s+.*\bupload\b/i,
      /\bcloud\s+storage\s+upload\b/i,
      /\bftp\s+put\b/i,
      /\bscp\s+.*@/i,
      /\brsync\s+.*@/i,
      /\baws\s+s3\s+cp\b/i,
      /\bgsutil\s+cp\b/i,
      /\bazure\s+storage\s+upload\b/i,
    ],
    categories: ['ai-agent', 'exfiltration', 'cloud'],
    action: 'warn',
  },
  {
    id: 'ai-api-call-sensitive',
    name: '调用敏感 API',
    description: '检测 AI 调用可能泄露数据的敏感 API',
    level: 'high',
    patterns: [
      /\bapi\.openai\.com\/.*\/files\b/i,
      /\bapi\.anthropic\.com\/.*\/messages\b/i,
      /\bPOST\s+.*\/api\/.*\b(key|secret|password|token)\b/i,
      /\bfetch\s*\(\s*['"`]https?:\/\/(?!localhost)/i,
      /\baxios\s*\.\s*(post|put|patch)\s*\(\s*['"`]https?:\/\/(?!localhost)/i,
      /\brequest\s*\(\s*\{[\s\S]*?method\s*:\s*['"`](POST|PUT|PATCH)/i,
    ],
    categories: ['ai-agent', 'api', 'exfiltration'],
    action: 'warn',
  },
  {
    id: 'ai-external-connection',
    name: '建立外部连接',
    description: '检测 AI 尝试建立外部网络连接',
    level: 'medium',
    patterns: [
      /\bwebsocket\s+connect\b/i,
      /\bsocket\s*\.\s*connect\b/i,
      /\bnet\s*\.\s*connect\b/i,
      /\bconnect\s+to\s+\d+\.\d+\.\d+\.\d+/i,
      /\bnew\s+WebSocket\s*\(/i,
      /\bio\s*\.\s*connect\b/i,
    ],
    categories: ['ai-agent', 'network'],
    action: 'warn',
  },
  {
    id: 'ai-credential-generation',
    name: '生成凭证',
    description: '检测 AI 尝试生成密钥或凭证',
    level: 'high',
    patterns: [
      /\bgenerate\s+(a\s+)?(api\s+)?key\b/i,
      /\bcreate\s+(a\s+)?(api\s+)?key\b/i,
      /\bgenerate\s+(ssh\s+)?key\s+pair\b/i,
      /\bssh-keygen\b/i,
      /\bopenssl\s+genrsa\b/i,
      /\bcreate\s+(access\s+)?token\b/i,
      /\bgenerate\s+secret\b/i,
    ],
    categories: ['ai-agent', 'credential'],
    action: 'warn',
  },
  {
    id: 'ai-env-modification',
    name: '环境变量修改',
    description: '检测 AI 尝试修改环境变量',
    level: 'high',
    patterns: [
      /\bexport\s+[A-Z_]+=/i,
      /\bsetenv\s+/i,
      /\bputenv\s+/i,
      /\bprocess\.env\.\w+\s*=/i,
      /\.bashrc|\.zshrc|\.profile/i,
      /\bPATH\s*=/i,
      /\bLD_PRELOAD\b/i,
      /\bLD_LIBRARY_PATH\b/i,
    ],
    categories: ['ai-agent', 'system', 'privilege'],
    action: 'warn',
  },
  {
    id: 'ai-sandbox-escape',
    name: '沙箱逃逸尝试',
    description: '检测可能的沙箱逃逸行为',
    level: 'critical',
    patterns: [
      /\bescape\s+sandbox\b/i,
      /\bbreak\s+out\s+of\s+sandbox\b/i,
      /\bbypass\s+sandbox\b/i,
      /\bdisable\s+sandbox\b/i,
      /\bchroot\s+escape\b/i,
      /\bnamespace\s+escape\b/i,
      /\bcontainer\s+escape\b/i,
      /\bdocker\s+escape\b/i,
      /\/proc\/self/i,
      /\bsyscall\s+/i,
    ],
    categories: ['ai-agent', 'privilege', 'intrusion'],
    action: 'block',
  },
  {
    id: 'ai-code-injection',
    name: '代码注入',
    description: '检测 AI 生成的代码注入尝试',
    level: 'critical',
    patterns: [
      /\beval\s*\(/i,
      /\bFunction\s*\(/i,
      /\bnew\s+Function\s*\(/i,
      /\bsetTimeout\s*\(\s*['"`]/i,
      /\bsetInterval\s*\(\s*['"`]/i,
      /\bexec\s*\(/i,
      /\bexecSync\s*\(/i,
      /\bspawn\s*\(/i,
      /\bspawnSync\s*\(/i,
      /\bchild_process\b/i,
      /\brequire\s*\(\s*['"`]child_process['"`]\s*\)/i,
    ],
    categories: ['ai-agent', 'code-injection', 'rce'],
    action: 'warn',
  },
  {
    id: 'ai-model-manipulation',
    name: '模型配置篡改',
    description: '检测尝试修改 AI 模型配置',
    level: 'high',
    patterns: [
      /\bmodify\s+model\s+config\b/i,
      /\bchange\s+model\s+settings\b/i,
      /\balter\s+model\s+behavior\b/i,
      /\.openclaw\/models\//i,
      /\.openclaw\/openclaw\.json.*model/i,
      /\btemperature\s*>\s*1/i,
      /\bmax_tokens\s*>\s*\d{5}/i,
    ],
    categories: ['ai-agent', 'config'],
    action: 'warn',
  },
  {
    id: 'ai-agent-deletion',
    name: '删除 Agent',
    description: '检测删除 OpenClaw Agent 的操作',
    level: 'high',
    patterns: [
      /\bdelete\s+agent\b/i,
      /\bremove\s+agent\b/i,
      /\bdestroy\s+agent\b/i,
      /\bopenclaw\s+agent\s+(delete|remove)/i,
      /\.openclaw\/agents\/.*\/config\.json/i,
    ],
    categories: ['ai-agent', 'destructive'],
    action: 'warn',
  },
  {
    id: 'ai-plugin-install',
    name: '安装插件',
    description: '检测 AI 自动安装插件',
    level: 'medium',
    patterns: [
      /\binstall\s+plugin\b/i,
      /\badd\s+plugin\b/i,
      /\bopenclaw\s+plugin\s+install/i,
      /\bnpm\s+install\s+.*openclaw-plugin/i,
      /\.openclaw\/plugins\/new/i,
    ],
    categories: ['ai-agent', 'plugin', 'security'],
    action: 'warn',
  },

  // ==================== 扩展网络操作 ====================
  {
    id: 'network-dns-exfil',
    name: 'DNS 数据外泄',
    description: '检测可能的 DNS 隧道数据外泄',
    level: 'high',
    patterns: [
      /\bdig\s+.*\@/i,
      /\bnslookup\s+.*\@/i,
      /\bdns\s+tunnel/i,
      /\bdnscat\b/i,
      /\bdns\s+exfil/i,
      /\bbase64\s+.*\.\w+\.com/i,
    ],
    categories: ['network', 'exfiltration'],
    action: 'warn',
  },
  {
    id: 'network-tor-usage',
    name: 'Tor 网络使用',
    description: '检测 Tor 网络相关操作',
    level: 'medium',
    patterns: [
      /\btor\b/i,
      /\btorsocks\b/i,
      /\.onion\b/i,
      /\bprivoxy\b/i,
    ],
    categories: ['network', 'anonymization'],
    action: 'warn',
  },
  {
    id: 'network-port-scan',
    name: '端口扫描',
    description: '检测端口扫描行为',
    level: 'high',
    patterns: [
      /\bnmap\s+/i,
      /\bmasscan\b/i,
      /\bport\s+scan\b/i,
      /\bnetcat\s+-z/i,
      /\bnc\s+-z/i,
      /\bzmap\b/i,
    ],
    categories: ['network', 'reconnaissance'],
    action: 'warn',
  },

  // ==================== 扩展文件操作 ====================
  {
    id: 'file-encrypt',
    name: '文件加密',
    description: '检测文件加密操作（可能是勒索软件行为）',
    level: 'high',
    patterns: [
      /\bgpg\s+.*--encrypt\b/i,
      /\bopenssl\s+.*enc\b/i,
      /\bencrypt\s+.*file/i,
      /\bencrypt\s+.*folder/i,
      /\b VeraCrypt\b/i,
      /\btruecrypt\b/i,
    ],
    categories: ['file', 'encryption'],
    action: 'warn',
  },
  {
    id: 'file-hidden-create',
    name: '创建隐藏文件',
    description: '检测创建隐藏文件或目录',
    level: 'medium',
    patterns: [
      /\btouch\s+\./i,
      /\bmkdir\s+\./i,
      /\bcreate\s+hidden\s+file/i,
      /\.\w+$/m,
      /\battr\s+\+h\b/i,
    ],
    categories: ['file', 'persistence'],
    action: 'log',
  },
  {
    id: 'file-log-tampering',
    name: '日志篡改',
    description: '检测修改或删除日志的行为',
    level: 'critical',
    patterns: [
      />\s*\/var\/log\//i,
      /\brm\s+.*\/var\/log\//i,
      /\btruncate\s+.*log/i,
      /\becho\s+.*>\s*.*\.log/i,
      /\bshred\b/i,
      /\bwipe\b/i,
      /\bsrm\b/i,
    ],
    categories: ['file', 'anti-forensics'],
    action: 'block',
  },

  // ==================== 扩展系统操作 ====================
  {
    id: 'system-cron-modify',
    name: '修改定时任务',
    description: '检测修改 crontab 的操作',
    level: 'high',
    patterns: [
      /\bcrontab\s+-e\b/i,
      /\bcrontab\s+-r\b/i,
      /\/etc\/cron/i,
      /\/var\/spool\/cron/i,
      /\bsystemctl\s+.*timer\b/i,
    ],
    categories: ['system', 'persistence'],
    action: 'warn',
  },
  {
    id: 'system-kernel-module',
    name: '内核模块操作',
    description: '检测加载或卸载内核模块',
    level: 'critical',
    patterns: [
      /\binsmod\b/i,
      /\brmmod\b/i,
      /\bmodprobe\b/i,
      /\bdepmod\b/i,
      /\/proc\/modules/i,
      /\/lib\/modules/i,
    ],
    categories: ['system', 'kernel'],
    action: 'block',
  },
  {
    id: 'system-iptables',
    name: '防火墙规则修改',
    description: '检测修改 iptables 规则',
    level: 'high',
    patterns: [
      /\biptables\s+/i,
      /\bip6tables\s+/i,
      /\bnftables\b/i,
      /\bnft\s+/i,
      /\bfirewall-cmd\b/i,
      /\bufw\s+/i,
    ],
    categories: ['system', 'firewall'],
    action: 'warn',
  },
];

export function getRulesByLevel(level: RiskLevel): DangerRule[] {
  return DANGER_RULES.filter(rule => rule.level === level);
}

export function getRulesByCategory(category: string): DangerRule[] {
  return DANGER_RULES.filter(rule => rule.categories.includes(category));
}
